version: 1.0

image:
  - ubuntu1804

services:
  - docker

before_build:
  - docker-compose -f docker-compose.yml up -d
  - sleep 20  # Подождем, чтобы сервисы успели запуститься

install:
  - java -jar -Dserver.port=8080 ./artifacts/aqa-shop.jar
  - chmod +x gradlew
  - sleep 20  # Подождем, чтобы сервис успел запуститься

build_script:
  - ./gradlew test --info -Dselenide.headless=true

after_build:
  - docker-compose -f docker-compose.yml down