version: 1.0

image:
  - ubuntu1804

services:
  - docker

before_build:
  - docker-compose -f docker-compose.yml up -d
  - chmod +x gradlew
  - sleep 20  # Подождем, чтобы сервисы успели запуститься

build_script:
  - java -jar ./artifacts/aqa-shop.jar
  - sleep 20  # Подождем, чтобы сервис успел запуститься
  - ./gradlew test --info -Dselenide.headless=true

after_build:
  - docker-compose -f docker-compose.yml down